import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Only English is hardcoded. All other languages are fetched at runtime from
// the backend NLLB-200 translation endpoint and cached in localStorage.
// See: frontend/src/hooks/useAutoTranslate.js
const en = {
  nav: {
    dashboard: "Dashboard", weather: "Weather", market: "Market Prices",
    recommend: "Crop Recommender", irrigation: "Irrigation",
    marketplace: "Marketplace", disease: "Disease Detection", advisory: "Crop Advisory",
    notifications: "Notifications", profile: "Profile", logout: "Logout",
    login: "Login", register: "Register",
  },
  landing: {
    hero_title: "Agrow Intelligence",
    hero_subtitle: "AI-powered farm management for Northeast India",
    hero_desc: "Weather forecasts, crop price predictions, disease detection, and expert farming advice — powered by AI agents.",
    get_started: "Get Started", features_title: "Everything your farm needs",
    f1_title: "Weather Intelligence", f1_desc: "AI-interpreted 7-day forecasts with planting and irrigation advice",
    f2_title: "Market Prices",        f2_desc: "10-crop price predictions with SELL, HOLD, WAIT decisions",
    f3_title: "Disease Detection",    f3_desc: "Upload a leaf photo for instant plant disease diagnosis",
    f4_title: "Crop Advisory",        f4_desc: "RAG-powered knowledge base with cultivar-specific guidance",
    f5_title: "AI Agent Reports",     f5_desc: "5-agent AI pipeline generates a unified daily farm intelligence report",
    f6_title: "Marketplace",          f6_desc: "Connect farmers and buyers directly — list, sell, and purchase crops",
    f7_title: "Crop Recommender",     f7_desc: "Random Forest ML recommends the best crop for your soil NPK, pH, temperature, and rainfall",
    f8_title: "Irrigation Advisor",   f8_desc: "Decision Tree model tells you when to irrigate and exactly how many mm of water to apply",
  },
  dashboard: {
    title: "Farm Dashboard", run_analysis: "Run AI Analysis", running: "Agents working...",
    latest_report: "Today's Farm Report", no_report: "No report yet. Click Run AI Analysis to generate one.",
    recommendations: "Top Recommendations", alerts: "Active Alerts",
    weather_summary: "Weather Summary", price_summary: "Price Summary",
  },
  weather: {
    title: "Weather Forecast", temperature: "Temperature", humidity: "Humidity",
    wind_speed: "Wind Speed", precipitation: "Precipitation", condition: "Condition",
    ai_advice: "AI Farming Advice", loading: "Loading forecast...",
    forecast_chart: "7-Day Temperature and Humidity Forecast",
    forecast_source: "Forecast generated by SARIMAX ML models",
    today_forecast: "Today's forecast",
  },
  market: {
    title: "Crop Market Prices", price_chart: "10-Day Price Forecast",
    chart_source: "Prices from SARIMAX models (ML crops) and seasonal formula (spices)",
    decisions: "Market Decisions", sell: "SELL", hold: "HOLD", wait: "WAIT",
    per_quintal: "per quintal", market_analysis: "Market Analysis",
    tab_vegetables: "Vegetables", tab_spices: "Spices and Herbs",
  },
  marketplace: {
    title: "Marketplace", add_product: "Add Product", my_listings: "My Listings",
    browse: "Browse Products", buy: "Buy", purchase: "Purchase",
    quantity: "Quantity", price: "Price", unit: "Unit", available: "Available",
    farmer: "Farmer", location: "Location",
  },
  disease: {
    title: "Plant Disease Detection", upload_prompt: "Drop a leaf photo here, or click to upload",
    analyzing: "Analyzing...", result: "Detection Result", crop: "Crop", disease: "Disease",
    confidence: "Confidence", treatment: "Recommended Treatment", healthy: "Plant is healthy!",
    tip: "For best results, take a clear photo of the affected leaf in natural light.",
  },
  advisory: {
    title: "Crop Advisory", placeholder: "Ask anything about your crops...",
    search: "Get Advice", searching: "Searching knowledge base...",
    no_result: "No specific information found. Try a different question.",
    examples: "Try asking:", ex1: "How to treat tomato blight?",
    ex2: "Best time to plant brinjal in Assam?", ex3: "How to increase cabbage yield?",
  },
  notifications: {
    title: "Notifications", no_notifications: "No notifications",
    mark_read: "Mark as read", delete: "Delete",
    weather: "Weather", price: "Price Alert", agent: "Farm Report",
    disease: "Disease Alert", system: "System",
  },
  profile: {
    title: "My Profile", username: "Username", email: "Email", role: "Role",
    location: "Location", crops: "My Crops", farm_size: "Farm Size (acres)",
    update: "Update Profile", farmer: "Farmer", buyer: "Buyer",
  },
  auth: {
    login_title: "Welcome back", register_title: "Create your account",
    email: "Email", password: "Password", username: "Username", role: "I am a",
    farmer: "Farmer", buyer: "Buyer", login_btn: "Sign in", register_btn: "Create account",
    no_account: "Don't have an account?", have_account: "Already have an account?",
    primary_crops: "Primary Crops (comma separated)", farm_location: "Farm Location",
  },
  common: {
    loading: "Loading...", error: "Something went wrong", retry: "Try again",
    save: "Save", cancel: "Cancel", back: "Back", view_all: "View all",
    translating: "Translating...",
  },
}

i18n.use(initReactI18next).init({
  resources: { en: { translation: en } },
  lng: localStorage.getItem('agrow_lang') || 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
})

export default i18n
